repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort
  - repo: local
    hooks:
      - id: requirements
        verbose: true
        name: Requirements
        language: python
        entry: poetry export --format=requirements.txt --without-hashes --output=requirements.txt
        pass_filenames: false
      - id: lock
        verbose: true
        name: lock
        language: python
        entry: poetry lock
        pass_filenames: false
  - repo: local
    hooks:
      - id: gen-jsonschema
        name: gen-jsonschema
        language: system
        entry: poetry run python util.py
        pass_filenames: false
